"""token blacklist

Revision ID: 59b569b67bb1
Revises: b9f7e4b0d1c8
Create Date: 2022-08-01 16:23:04.388769

"""
from alembic import op
import sqlalchemy as sa
import ormar
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59b569b67bb1'
down_revision = 'b9f7e4b0d1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invalid_token',
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('user_id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_invalid_token_token'), 'invalid_token', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invalid_token_token'), table_name='invalid_token')
    op.drop_table('invalid_token')
    # ### end Alembic commands ###
